version: "3"

services:
  www:
    image: ghcr.io/leslie-wong-h/trace.moe-www:latest
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_ENDPOINT=${NEXT_PUBLIC_API_ENDPOINT}
      - NEXT_PUBLIC_MEDIA_ENDPOINT=${NEXT_PUBLIC_MEDIA_ENDPOINT}
    ports:
      - ${WWW_PORT}:3000
    networks:
      trace_moe_net:


  media:
    image: ghcr.io/leslie-wong-h/trace.moe-media:latest
    restart: unless-stopped
    environment:
      - TRACE_MEDIA_SALT=${TRACE_MEDIA_SALT}
      - TRACE_API_SECRET=${TRACE_API_SECRET}
    ports:
      - ${MEDIA_PORT}:3000
    volumes:
      - type: bind
        source: ${MEDIA_DIR}
        target: /mnt/
    networks:
      trace_moe_net:


  api:
    image: ghcr.io/leslie-wong-h/trace.moe-api:latest
    depends_on:
      - redis
      - mariadb
      - liresolr
    restart: unless-stopped
    environment:
      - TRACE_ALGO=cl
      - SOLA_DB_HOST=mariadb
      - SOLA_DB_PORT=3306
      - SOLA_DB_USER=root
      - SOLA_DB_PWD=${MARIADB_ROOT_PASSWORD}
      - SOLA_DB_NAME=sola
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=3000
      - SOLA_SOLR_LIST=http://172.17.0.1:${SOLR_PORT}/solr/
      - SOLA_SOLR_SIZE=4
      - TRACE_MEDIA_URL=${NEXT_PUBLIC_MEDIA_ENDPOINT}
      - TRACE_MEDIA_SALT=${TRACE_MEDIA_SALT}
      - TRACE_API_SECRET=${TRACE_API_SECRET}
      - HASH_PATH=/mnt/hash
    ports:
      - ${API_PORT}:3000
    volumes:
      - type: bind
        source: ${HASH_DIR}
        target: /mnt/hash
    networks:
      trace_moe_net:


  adminer:
    image: adminer:latest
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
      - ADMINER_DEFAULT_USER=root
      - ADMINER_DEFAULT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      trace_moe_net:


  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      trace_moe_net:


  redis:
    image: redis:latest
    networks:
      trace_moe_net:


  liresolr:
    image: ghcr.io/leslie-wong-h/liresolr:latest
    command: solr-precreate cl_0 /opt/solr/server/solr/configsets/liresolr
    restart: unless-stopped
    ports:
      - ${SOLR_PORT}:8983
    volumes:
      - type: bind
        source: ${SOLR_DIR}
        target: /var/solr
    environment:
      - SOLR_HEAP=2G
    networks:
      trace_moe_net:


  hasher:
    image: ghcr.io/leslie-wong-h/trace.moe-worker-hasher:latest
    restart: unless-stopped
    environment:
      - TRACE_API_URL=http://172.17.0.1:${API_PORT}
      - TRACE_API_SECRET=${TRACE_API_SECRET}
      - TRACE_MEDIA_URL=http://172.17.0.1:${MEDIA_PORT}
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    networks:
      trace_moe_net:


  loader:
    image: ghcr.io/leslie-wong-h/trace.moe-worker-loader:latest
    restart: unless-stopped
    environment:
      - TRACE_API_URL=http://172.17.0.1:${API_PORT}
      - TRACE_API_SECRET=${TRACE_API_SECRET}
      - TRACE_MEDIA_URL=http://172.17.0.1:${MEDIA_PORT}
    networks:
      trace_moe_net:


  watcher:
    image: ghcr.io/leslie-wong-h/trace.moe-worker-watcher:latest
    restart: unless-stopped
    environment:
      - TRACE_API_URL=http://172.17.0.1:${API_PORT}
      - TRACE_API_SECRET=${TRACE_API_SECRET}
      - TRACE_MEDIA_URL=http://172.17.0.1:${MEDIA_PORT}
      - TRACE_WATCH_PATH=/mnt/
    volumes:
      - type: bind
        source: ${WATCH_DIR}
        target: /mnt/
    networks:
      trace_moe_net:


networks:
  trace_moe_net:
    driver: bridge
