version: "3.5"

services:
  www:
    image: ghcr.io/leslie-wong-h/trace.moe-www:latest
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_ENDPOINT=${NEXT_PUBLIC_API_ENDPOINT}
      - NEXT_PUBLIC_MEDIA_ENDPOINT=${NEXT_PUBLIC_MEDIA_ENDPOINT}
      - NEXT_PUBLIC_ANILIST_ENDPOINT=${NEXT_PUBLIC_ANILIST_ENDPOINT}
    ports:
      - ${WWW_PORT}:3000
    networks:
      trace_moe_net:


  media:
    image: ghcr.io/leslie-wong-h/trace.moe-media:latest
    restart: unless-stopped
    environment:
      - TRACE_MEDIA_SALT=${TRACE_MEDIA_SALT}
      - TRACE_API_SECRET=${TRACE_API_SECRET}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    ports:
      - ${MEDIA_PORT}:3000
    volumes:
      - type: bind
        source: ${MEDIA_DIR}
        target: /mnt/
    networks:
      trace_moe_net:


  api:
    image: ghcr.io/leslie-wong-h/trace.moe-api:latest
    depends_on:
      - redis
      - mariadb
      - liresolr
    restart: unless-stopped
    environment:
      - TRACE_ALGO=cl
      - SOLA_DB_HOST=mariadb
      - SOLA_DB_PORT=3306
      - SOLA_DB_USER=root
      - SOLA_DB_PWD=${MARIADB_ROOT_PASSWORD}
      - SOLA_DB_NAME=sola
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=3000
      - SOLA_SOLR_LIST=http://172.17.0.1:${SOLR_PORT}/solr/
      - SOLA_SOLR_SIZE=4
      - TRACE_MEDIA_URL=${NEXT_PUBLIC_MEDIA_ENDPOINT}
      - TRACE_MEDIA_SALT=${TRACE_MEDIA_SALT}
      - TRACE_API_SECRET=${TRACE_API_SECRET}
      - HASH_PATH=/mnt/hash
      - SEARCHER_URL=http://172.17.0.1:${SEARCHER_PORT}
    ports:
      - ${API_PORT}:3000
    volumes:
      - type: bind
        source: ${HASH_DIR}
        target: /mnt/hash
    networks:
      trace_moe_net:


  adminer:
    image: adminer:latest
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
      - ADMINER_DEFAULT_USER=root
      - ADMINER_DEFAULT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      trace_moe_net:


  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - type: bind
        source: ${MYSQL_DIR}
        target: /var/lib/mysql
    networks:
      trace_moe_net:


  redis:
    image: redis:latest
    networks:
      trace_moe_net:


  liresolr:
    image: ghcr.io/leslie-wong-h/liresolr:latest
    command: solr-precreate cl_0 /opt/solr/server/solr/configsets/liresolr
    restart: unless-stopped
    ports:
      - ${SOLR_PORT}:8983
    volumes:
      - type: bind
        source: ${SOLR_DIR}
        target: /var/solr
    environment:
      - SOLR_HEAP=2G
    networks:
      trace_moe_net:


  hasher:
    image: ghcr.io/leslie-wong-h/trace.moe-worker-hasher:latest
    restart: unless-stopped
    environment:
      - TRACE_API_URL=http://172.17.0.1:${API_PORT}
      - TRACE_API_SECRET=${TRACE_API_SECRET}
      - TRACE_MEDIA_URL=http://172.17.0.1:${MEDIA_PORT}
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    networks:
      trace_moe_net:


  loader:
    image: ghcr.io/leslie-wong-h/trace.moe-worker-loader:latest
    restart: unless-stopped
    environment:
      - TRACE_API_URL=http://172.17.0.1:${API_PORT}
      - TRACE_API_SECRET=${TRACE_API_SECRET}
      - TRACE_MEDIA_URL=http://172.17.0.1:${MEDIA_PORT}
      - MILVUS_URL=172.17.0.1:${MILVUS_PORT}
    networks:
      trace_moe_net:


  watcher:
    image: ghcr.io/leslie-wong-h/trace.moe-worker-watcher:latest
    restart: unless-stopped
    environment:
      - TRACE_API_URL=http://172.17.0.1:${API_PORT}
      - TRACE_API_SECRET=${TRACE_API_SECRET}
      - TRACE_MEDIA_URL=http://172.17.0.1:${MEDIA_PORT}
      - TRACE_WATCH_PATH=/mnt/
    volumes:
      - type: bind
        source: ${WATCH_DIR}
        target: /mnt/
    networks:
      trace_moe_net:


  searcher:
    image: ghcr.io/leslie-wong-h/trace.moe-worker-searcher:latest
    restart: unless-stopped
    ports:
      - ${SEARCHER_PORT}:19531
    environment:
      - TRACE_ALGO=cl
      - SOLA_SOLR_LIST=http://172.17.0.1:${SOLR_PORT}/solr/
      - SEARCHER_URL=http://172.17.0.1:${SEARCHER_PORT}
      - MILVUS_URL=172.17.0.1:${MILVUS_PORT}
    networks:
      trace_moe_net:


  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    restart: unless-stopped
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    ports:
      - "2379:2379"
    networks:
      trace_moe_net:


  # minio:
  #   # Local Minio Server
  #   container_name: milvus-minio
  #   image: minio/minio:RELEASE.2022-03-17T06-34-49Z
  #   environment:
  #     MINIO_ACCESS_KEY: minioadmin
  #     MINIO_SECRET_KEY: minioadmin
  #   volumes:
  #     - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
  #   command: minio server /minio_data
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "curl",
  #         "-f",
  #         "http://localhost:9000/minio/health/live"
  #       ]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   networks:
  #     trace_moe_net:


  minio:
    # Remote Minio Gateway
    container_name: milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_KEY}
      - MINIO_ETCD_ENDPOINTS=http://172.17.0.1:2379
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio gateway s3 ${AWS_ENDPOINT_URL} --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - "etcd"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      trace_moe_net:


  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.1.2
    restart: unless-stopped
    command: [ "milvus", "run", "standalone" ]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ${DOCKER_VOLUME_DIRECTORY:-.}/milvus.yaml:/milvus/configs/milvus.yaml
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      trace_moe_net:


networks:
  trace_moe_net:
    driver: bridge
